### ISSUE TITLE
runtest.py error output could be improved

### ISSUE THREAD

**Issue by henrychoi7** [namhyung/uftrace#1109]
When running test scripts with `runtest.py`, some users could execute it in unexpected way and encounter errors like below.
```
$ ./tests/runtest.py
Start 0 tests with 1 worker
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os

Traceback (most recent call last):
  File "./tests/runtest.py", line 801, in <module>
    print_test_report(color, shared)
  File "./tests/runtest.py", line 670, in print_test_report
    percent = 100.0 * success / shared.total
ZeroDivisionError: float division by zero
```
**OR**
```
$ ./tests/runtest.py 21
cannot find testcase for : 21
```

But If I run `runtest.py` in the same `tests` directory, it starts with all 234 test cases as follows (executing with arguments works fine too):
```
$ ./runtest.py
Start 234 tests with 1 worker
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
001 basic               : OK OK OK OK OK OK OK OK OK OK
...
```

Therefore, I thought the error message could be shorten (or add some exception) like below.
**Example (Not a solution):**
```
diff --git a/tests/runtest.py b/tests/runtest.py
index 1ddc8b79..43a0aa58 100755
--- a/tests/runtest.py
+++ b/tests/runtest.py
@@ -667,7 +667,10 @@ def print_test_header(opts, flags, ftests):

 def print_test_report(color, shared):
     success = shared.stats[TestBase.TEST_SUCCESS] + shared.stats[TestBase.TEST_SUCCESS_FIXED]
-    percent = 100.0 * success / shared.total
+    try:
+        percent = 100.0 * success / shared.total
+    except ZeroDivisionError:
+        percent = 0

     print("")
     print("runtime test stats")
```
**Result:**
```
Start 0 tests with 1 worker
Test case                 pg             finstrument-fu
------------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os


runtime test stats
====================
total     0  Tests executed (success: 0.00%)
  OK:     0  Test succeeded
  OK:     0  Test succeeded (with some fixup)
  NG:     0  Different test result
  NZ:     0  Non-zero return value
  SG:     0  Abnormal exit by signal
  TM:     0  Test ran too long
  BI:     0  Build failed
  LA:     0  Unsupported Language
  SK:     0  Skipped
```
It doesn't show the error message but perhaps, enforcing a different cwd might be a solution but I'm not sure what is a better way to fix this.

**Comment by namhyung** [comment]
I'm ok with the above, please send a PR.

**Comment by henrychoi7** [comment]
In addition, Is it okay to add more description for the error like below?

**Problem:**
```
$ ./tests/runtest.py 21
cannot find testcase for : 21
```
**Example (Not a solution):**
```
diff --git a/tests/runtest.py b/tests/runtest.py
index 1ddc8b79..9ea5a643 100755
--- a/tests/runtest.py
+++ b/tests/runtest.py
@@ -724,7 +727,7 @@ if __name__ == "__main__":
             arg.worker = min(arg.worker, len(testcases))
         finally:
             if len(testcases) == 0:
-                print("cannot find testcase for : %s" % arg.case)
+                print("cannot find testcase for '%s': Please check your cwd or testcase name." % arg.case)
                 sys.exit(0)

     opts = ' '.join(sorted(['O' + o for o in arg.opts]))
```
**Result:**
```
$ ./tests/runtest.py 21
cannot find testcase for '21': Please check your cwd or testcase name.
```
Including the fix above, I think it would be more precise to determine what is wrong.

**Comment by namhyung** [comment]
Looks good.
