### ISSUE TITLE
ASAN errors in script-python

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1210]
There is an ASAN error as follows.
```
$ make ASAN=1 install

$ gcc -pg -g -o t-arg tests/s-arg.c

$ uftrace record -a t-arg

$ uftrace script -S scripts/dump.py --no-pager
uftrace_begin(ctx)
  record  : False
  version : v0.9.4-129-g4be7 ( dwarf python luajit tui perf sched dynamic )
  cmds    :

17910610.546322424  34457: [entry] __monstartup(4005b0) depth: 0
17910610.546323121  34457: [exit ] __monstartup(4005b0) depth: 0
17910610.546324914  34457: [entry] __cxa_atexit(4005d0) depth: 0
17910610.546325298  34457: [exit ] __cxa_atexit(4005d0) depth: 0
17910610.546325981  34457: [entry] main(400a6f) depth: 0
  args[0] <class 'int'>: 1
  args[1] <class 'int'>: 140727876517768
17910610.546326972  34457: [entry] foo(40076c) depth: 1
  args[0] <class 'int'>: 3
=================================================================
==34847==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000a8892 at pc 0x7ffb47655260 bp 0x7ffe54f558d0 sp 0x7ffe54f55078
READ of size 4 at 0x6020000a8892 thread T0
    #0 0x7ffb4765525f  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xd925f)
    #1 0x489f7e in setup_argument_context /home/honggyu/uftrace/utils/script-python.c:498
    #2 0x48a7a7 in python_uftrace_entry /home/honggyu/uftrace/utils/script-python.c:592
    #3 0x41395a in run_script_for_rstack /home/honggyu/uftrace/cmds/script.c:78
    #4 0x4146de in command_script /home/honggyu/uftrace/cmds/script.c:192
    #5 0x40c820 in main /home/honggyu/uftrace/uftrace.c:1366
    #6 0x7ffb45f0d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #7 0x405e08 in _start (/home/honkim01/usr/bin/uftrace+0x405e08)

0x6020000a8892 is located 0 bytes to the right of 2-byte region [0x6020000a8890,0x6020000a8892)
allocated by thread T0 here:
    #0 0x7ffb47688078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x489e85 in setup_argument_context /home/honggyu/uftrace/utils/script-python.c:491
    #2 0x48a7a7 in python_uftrace_entry /home/honggyu/uftrace/utils/script-python.c:592
    #3 0x41395a in run_script_for_rstack /home/honggyu/uftrace/cmds/script.c:78
    #4 0x4146de in command_script /home/honggyu/uftrace/cmds/script.c:192
    #5 0x40c820 in main /home/honggyu/uftrace/uftrace.c:1366
    #6 0x7ffb45f0d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xd925f)
Shadow bytes around the buggy address:
  0x0c048000d0c0: fa fa 00 00 fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c048000d0d0: fa fa fd fa fa fa fd fd fa fa fd fd fa fa fd fa
  0x0c048000d0e0: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fd
  0x0c048000d0f0: fa fa 00 04 fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c048000d100: fa fa fd fa fa fa 00 fa fa fa fd fa fa fa 04 fa
=>0x0c048000d110: fa fa[02]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000d120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000d130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000d140: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000d150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000d160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==34847==ABORTING
```
It can be fixed by #1209, but it still shows some memory leak as follows.
```
$ uftrace script -S scripts/dump.py --no-pager
uftrace_begin(ctx)
  record  : False
  version : v0.9.4-129-g4be7 ( dwarf python luajit tui perf sched dynamic )
  cmds    :

17910610.546322424  34457: [entry] __monstartup(4005b0) depth: 0
17910610.546323121  34457: [exit ] __monstartup(4005b0) depth: 0
17910610.546324914  34457: [entry] __cxa_atexit(4005d0) depth: 0
17910610.546325298  34457: [exit ] __cxa_atexit(4005d0) depth: 0
17910610.546325981  34457: [entry] main(400a6f) depth: 0
  args[0] <class 'int'>: 1
  args[1] <class 'int'>: 140727876517768
17910610.546326972  34457: [entry] foo(40076c) depth: 1
  args[0] <class 'int'>: 3
        ...
=================================================================
==35605==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 259056 byte(s) in 97 object(s) allocated from:
    #0 0x7fdda36d3078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x7fdd9db0f524  (<unknown module>)

Direct leak of 1576 byte(s) in 3 object(s) allocated from:
    #0 0x7fdda36d3078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x7fdd9db10187  (<unknown module>)

Direct leak of 768 byte(s) in 1 object(s) allocated from:
    #0 0x7fdda36d34ae in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c4ae)
    #1 0x7fdd9dbf914e  (<unknown module>)

Direct leak of 692 byte(s) in 1 object(s) allocated from:
    #0 0x7fdda36d3078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x7fdd9dc193e5  (<unknown module>)

Direct leak of 640 byte(s) in 1 object(s) allocated from:
    #0 0x7fdda36d3078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x7fdd9db0fb9f  (<unknown module>)

Direct leak of 140 byte(s) in 4 object(s) allocated from:
    #0 0x7fdda36d3078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x7fdd9db0efec  (<unknown module>)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7fdda36d3078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x7fdd9db98194  (<unknown module>)

Indirect leak of 32002 byte(s) in 31 object(s) allocated from:
    #0 0x7fdda36d3078 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c078)
    #1 0x7fdd9db0f524  (<unknown module>)

SUMMARY: AddressSanitizer: 294906 byte(s) leaked in 139 allocation(s).
```

**Comment by namhyung** [comment]
I think we fixed this in 444069d.  Other leaks came from unknown module are hard to fix.
