### ISSUE TITLE
memory leak in perf event with time filter

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#1212]
We can record and replay as follows.
```
$ gcc -o t-taskname -pg tests/s-taskname.c -pthread

$ uftrace record t-taskname

$ uftrace replay --no-pager
# DURATION     TID     FUNCTION
   0.513 us [ 36062] | __monstartup();
   0.420 us [ 36062] | __cxa_atexit();
            [ 36062] | main() {
            [ 36062] |   task_name1() {
            [ 36062] |     prctl() {
            [ 36062] |       /* linux:task-name (name=foo) */
  11.947 us [ 36062] |     } /* prctl */
  12.345 us [ 36062] |   } /* task_name1 */
            [ 36062] |   task_name2() {
   0.507 us [ 36062] |     pthread_self();
            [ 36062] |     pthread_setname_np() {
            [ 36062] |       /* linux:task-name (name=bar) */
   3.119 us [ 36062] |     } /* pthread_setname_np */
   4.031 us [ 36062] |   } /* task_name2 */
  16.732 us [ 36062] | } /* main */
```
However, it shows a memory leak when replaying with time-filter as follows.
```
$ uftrace replay -t 1ns --no-pager
# DURATION     TID     FUNCTION
   0.578 us [  7833] | __monstartup();
   0.484 us [  7833] | __cxa_atexit();
            [  7833] | main() {
            [  7833] |   task_name1() {
            [  7833] |     prctl() {
            [  7833] |       /* linux:task-name (name=foo) */
   7.500 us [  7833] |     } /* prctl */
   7.906 us [  7833] |   } /* task_name1 */
            [  7833] |   task_name2() {
   0.537 us [  7833] |     pthread_self();
            [  7833] |     pthread_setname_np() {
            [  7833] |       /* linux:task-name (name=bar) */
   3.313 us [  7833] |     } /* pthread_setname_np */
   4.251 us [  7833] |   } /* task_name2 */
  12.497 us [  7833] | } /* main */

=================================================================
==7832==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 19 byte(s) in 3 object(s) allocated from:
    #0 0x7fa5e7174d0d in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x94d0d)
    #1 0x49a19d in process_perf_event /home/honggyu/uftrace/utils/perf.c:580
    #2 0x4bfea5 in __read_rstack /home/honggyu/uftrace/utils/fstack.c:2159
    #3 0x4c0c52 in peek_rstack /home/honggyu/uftrace/utils/fstack.c:2329
    #4 0x4309e4 in command_replay /home/honggyu/uftrace/cmds/replay.c:1185
    #5 0x43d9b4 in command_live /home/honggyu/uftrace/cmds/live.c:168
    #6 0x40c730 in main /home/honggyu/uftrace/uftrace.c:1348
    #7 0x7fa5e5a7182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 19 byte(s) leaked in 3 allocation(s).
```

**Comment by namhyung** [comment]
Thanks for reporting this.  Indeed the perf event processing is different when time filter is enabled.  I will take a look later..
