### ISSUE TITLE
Random crashes in replay with kernel events

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#123]
@namhyung Please take a look the below crash log:
```
$ sudo uftrace -k -E sched:*@kernel record --force /bin/sleep 1

$ uftrace replay
uftrace: /home/honggyu/work/uftrace/git/uftrace/utils/fstack.c:816: consume_first_rstack_list: Assertion `node->args.data == NULL' failed.
# DURATION    TID     FUNCTION
Aborted (core dumped)
```
Here is the backtrace log:
```
 806│ void consume_first_rstack_list(struct uftrace_rstack_list *list)
 807│ {
 808│         struct uftrace_rstack_list_node *node;
 809│
 810│         assert(list->count > 0);
 811│
 812│         node = list_first_entry(&list->read, typeof(*node), list);
 813│         list_move(&node->list, &list->unused);
 814│
 815│         if (node->rstack.more)
 816├───────────────> assert(node->args.data == NULL);
 817│
 818│         list->count--;
 819│ }
/home/honggyu/work/uftrace/git/uftrace/utils/fstack.c

(gdb) bt
    ...
#3  0x00007ffff707bc82 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000428e0d in consume_first_rstack_list (list=0x670510) at /home/honggyu/work/uftrace/git/uftrace/utils/fstack.c:816
#5  0x000000000042f22e in read_kernel_stack (handle=0x7fffffffe100, taskp=0x7fffffffe060) at /home/honggyu/work/uftrace/git/uftrace/utils/kernel.c:1574
#6  0x000000000042aa9b in __read_rstack (handle=0x7fffffffe100, taskp=0x7fffffffe0e0, consume=true) at /home/honggyu/work/uftrace/git/uftrace/utils/fstack.c:1543
#7  0x000000000042acbd in read_rstack (handle=0x7fffffffe100, task=0x7fffffffe0e0) at /home/honggyu/work/uftrace/git/uftrace/utils/fstack.c:1623
#8  0x0000000000413d72 in command_replay (argc=3, argv=0x7fffffffe4f8, opts=0x7fffffffe2f0) at /home/honggyu/work/uftrace/git/uftrace/cmd-replay.c:950
#9  0x0000000000405895 in main (argc=3, argv=0x7fffffffe4f8) at /home/honggyu/work/uftrace/git/uftrace/uftrace.c:849
```

**Comment by namhyung** [comment]
Hmm.. I need to look at the kernel source why it records from unrelated task.  But uftrace still needs to protect from broken kernel data.  Could you please test attached patch can fix the problem?


[kernel-free-invalid-rstack-list-data.patch.txt](https://github.com/namhyung/uftrace/files/1185744/kernel-free-invalid-rstack-list-data.patch.txt)

**Comment by honggyukim** [comment]
I've tested it after fixing a minor change from your change.
```
diff --git a/utils/kernel.c b/utils/kernel.c
index 10edefa..0ce874c 100644
--- a/utils/kernel.c
+++ b/utils/kernel.c
@@ -14,6 +14,7 @@
 #include <fnmatch.h>
 #include <sys/stat.h>
 #include <sys/mman.h>
+#include <assert.h>

 /* This should be defined before #include "utils.h" */
 #define PR_FMT     "kernel"
@@ -1575,7 +1576,7 @@ retry:
                kernel->rstack_valid[first_cpu] = false;

                if (first_rstack->more) {
-                       node = list_first_entry(&kernel->rstack_list[cpu].read,
+                       node = list_first_entry(&kernel->rstack_list[first_cpu].read,
                                                typeof(*node), list);
                        assert(node->args.data);

```
The problem is gone with the patch you gave. Thanks!

**Comment by namhyung** [comment]
Oops, there was a copy-n-paste error.  Thanks for the fix and test.
