### ISSUE TITLE
importing matplotlib and numpy

### ISSUE THREAD

**Issue by honggyukim** [namhyung/uftrace#145]
I've seen some problems importing matplotlib and numpy for plotting charts. It may be ubuntu dependent but here is the sequence I tested.
```
$ sudo apt-get install python-matplotlib python-numpy python-scipy
```
Then the below command works fine.
```
$ python -c 'import numpy'
```
So I wanted to use matplotlib and numpy in uftrace script. Due to missing system import path setting, it needs to apply some changes below:
```
diff --git a/utils/script-python.c b/utils/script-python.c
index 8113f91..0ec092e 100644
--- a/utils/script-python.c
+++ b/utils/script-python.c
@@ -94,9 +94,18 @@ static char *remove_py_suffix(char *py_name)
 static int import_python_module(char *py_pathname)
 {
        char py_sysdir[PATH_MAX];
-       if (absolute_dirname(py_pathname, py_sysdir) == NULL)
+       char py_dir[PATH_MAX];
+       if (absolute_dirname(py_pathname, py_dir) == NULL)
                return -1;
 
+       sprintf(py_sysdir, "%s:%s:%s:%s:%s", py_dir,
+               "/usr/lib/python2.7",
+               "/usr/lib/python2.7/dist-packages",
+               "/usr/lib/python2.7/lib-dynload",
+               "/usr/local/lib/python2.7",
+               "/usr/local/lib/python2.7/dist-packages",
+               "/usr/local/lib/python2.7/lib-dynload");
+
        /* Set path to import a python module. */
        __PySys_SetPath(py_sysdir);
        pr_dbg("PySys_SetPath(\"%s\") is done!\n", py_sysdir);
```
I tried again running the below script.
```
$ cat test.py
import numpy
```
But it shows the following error:
```
$ uftrace --force -S test.py /usr/bin/uptime
Traceback (most recent call last):
  File "/home/honggyu/src/uftrace/git/uftrace/scripts/test.py", line 1, in <module>
    import numpy
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

WARN: test.py cannot be imported!
 17:33:31 up 26 days,  3:30, 56 users,  load average: 0.12, 0.10, 0.09
# DURATION    TID     FUNCTION
   6.261 us [28622] | setlocale();
   1.161 us [28622] | bindtextdomain();
   0.779 us [28622] | textdomain();
   0.203 us [28622] | __cxa_atexit();
   1.237 us [28622] | getopt_long();
 153.818 us [28622] | print_uptime();
   0.286 us [28622] | __fpending();
   0.154 us [28622] | ferror();
   2.494 us [28622] | fclose();
   0.114 us [28622] | __fpending();
   0.094 us [28622] | ferror();
   0.352 us [28622] | fclose();
```
I found that the thing is multiarray is not `.py` script but `.so` binary file. In this environment, the below statement in `numpy/core/__init__.py` fails.
```
try:
    from . import multiarray
except ImportError:
    msg = """
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
"""
    raise ImportError(msg)
```
I see that multiarray is open when running it in python interpreter as usual.
```
$ strace -F python -c 'import numpy' 2>&1 | grep "^open(" | grep multiarray
open("/usr/lib/python2.7/dist-packages/numpy/core/multiarray.x86_64-linux-gnu.so", O_RDONLY) = 8
open("/usr/lib/python2.7/dist-packages/numpy/core/multiarray.x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 9
```
It needs to be investigated further.

**Comment by honggyukim** [comment]
I posted a question in numpy community and try to find a solution.
https://github.com/numpy/numpy/issues/9655

**Comment by honggyukim** [comment]
@namhyung Please take a look at #146 !
