### ISSUE TITLE
Test failure with list index out of range

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1522]
In the [nightly test setup](../blob/master/.github/workflows/nightly-test.yml), it runs `make test -j1` at 4am.  But it fails like below.

```
124 exception           : NG NG OK NG OK NG NG OK OK OK
Traceback (most recent call last):
  File "./runtest.py", line 905, in <module>
    results = run_single_case(name, flags, opts.split(), arg)
  File "./runtest.py", line 706, in run_single_case
    ret, dif = tc.run(case, cflags, arg.diff, timeout)
  File "/home/runner/work/uftrace/uftrace/tests/runtest.py", line 578, in run
    result_tested = self.sort(result_origin)  # for python3
  File "/home/runner/work/uftrace/uftrace/tests/runtest.py", line 451, in sort
    return func(self, output, ignore_children)
  File "/home/runner/work/uftrace/uftrace/tests/runtest.py", line 353, in report_sort
    result.append('%s %s' % (line[4], line[5]))
IndexError: list index out of range
make[1]: *** [Makefile:33: test_all] Error 1
make: *** [Makefile:361: test] Error 2
Error: Process completed with exit code 2.
```

**Comment by honggyukim** [comment]
I've tried to reproduce the problem, but couldn't reproduce it. Maybe the output of `125 report_range` is incorrect here so parsing is failed.

**Comment by namhyung** [comment]
Hmm.. I've added the on-demand test and [it was fine](https://github.com/namhyung/uftrace/actions/runs/2844510266).  The only difference is I passed "-v" option.

**Comment by honggyukim** [comment]
It might be related to https://github.com/namhyung/uftrace/issues/1509#issuecomment-1214722736.

**Comment by namhyung** [comment]
Yeah, looks that relevant.  We really need to fix the parse error.
