### ISSUE TITLE
script: Cannot handle exceptions on `uftrace_begin`, `uftrace_entry` function

### ISSUE THREAD

**Issue by mirusu400** [namhyung/uftrace#1826]
When exceptions are caught in the `uftrace_begin` or `uftrace_entry` functions, uftrace simply ignores the errors and proceeds to run other scripts.

```python
def uftrace_begin(ctx):
    raise Exception("Begin exception")

def uftrace_entry(ctx):
    raise Exception("Entry exception")

def uftrace_exit(ctx):
    print(ctx)

def uftrace_end():
    print("end")
```

```bash
(venv) ubuntu@ubuntu:~$ uftrace script -S ~/uftrace/scripts/crash.py
{'tid': 114314, 'depth': 0, 'timestamp': 57551582064790, 'address': 94630999851152, 'name': '<invalid value>', 'duration': 875}
{'tid': 114314, 'depth': 0, 'timestamp': 57551582066287, 'address': 94630999851168, 'name': '<invalid value>', 'duration': 316}
{'tid': 114314, 'depth': 7, 'timestamp': 57551582069584, 'address': 94630999851548, 'name': '<invalid value>', 'duration': 97}
{'tid': 114314, 'depth': 7, 'timestamp': 57551582070080, 'address': 94630999851548, 'name': '<invalid value>', 'duration': 65}
{'tid': 114314, 'depth': 6, 'timestamp': 57551582070227, 'address': 94630999851548, 'name': 'fib', 'duration': 820}
{'tid': 114314, 'depth': 6, 'timestamp': 57551582070444, 'address': 94630999851548, 'name': '<invalid value>', 'duration': 66}
{'tid': 114314, 'depth': 5, 'timestamp': 57551582070562, 'address': 94630999851548, 'name': 'fib', 'duration': 1237}
...
{'tid': 114314, 'depth': 4, 'timestamp': 57551582076656, 'address': 94630999851548, 'name': '<invalid value>', 'duration': 77}
{'tid': 114314, 'depth': 3, 'timestamp': 57551582076735, 'address': 94630999851548, 'name': 'fib', 'duration': 790}
{'tid': 114314, 'depth': 2, 'timestamp': 57551582076813, 'address': 94630999851548, 'name': 'fib', 'duration': 2627}
{'tid': 114314, 'depth': 1, 'timestamp': 57551582076891, 'address': 94630999851548, 'name': 'fib', 'duration': 7994}
{'tid': 114314, 'depth': 0, 'timestamp': 57551582076987, 'address': 94630999851618, 'name': 'main', 'duration': 8281}
end
```

It seems that both the `uftrace_exit` and `uftrace_end` functions trace exceptions correctly.

**uftrace_exit**

```python
def uftrace_exit(ctx):
    raise Exception("Exit exception")
```

```bash
(venv) ubuntu@ubuntu:~$ uftrace script -S ~/uftrace/scripts/crash.py
Traceback (most recent call last):
  File "/home/ubuntu/uftrace/scripts/crash.py", line 11, in uftrace_exit
    raise Exception("Exit exception")
Exception: Exit exception
(venv) ubuntu@ubuntu:~$ 
```

**uftrace_end**

```python
def uftrace_end():
    raise Exception("End exception")
```

```bash
(venv) ubuntu@ubuntu:~$ uftrace script -S ~/uftrace/scripts/crash.py
Traceback (most recent call last):
  File "/home/ubuntu/uftrace/scripts/crash.py", line 11, in uftrace_end
    raise Exception("End exception")
Exception: End exception
```

**Comment by paranlee** [comment]
Can you comments on your development environments?

**Comment by paranlee** [comment]
I will check your `venv`.
