### ISSUE TITLE
Segmentation fault with report  diff mode

### ISSUE THREAD

**Issue by sagarramdev173** [namhyung/uftrace#1970]
gdb -c core.2371153 /usr/local/bin/uftrace

GNU gdb (GDB) Red Hat Enterprise Linux 8.2-20.0.2.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/uftrace...done.
[New LWP 2371153]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `uftrace report --avg-total --diff=uftrace.data.old/'.

Program terminated with signal SIGSEGV, Segmentation fault.
#0  add_field (output_fields=0x668800 <output_fields>, field=0x0) at /home/opc/uftrace/utils/field.c:80
80              if (field->used)
Missing separate debuginfos, use: yum debuginfo-install brotli-1.0.6-3.el8.x86_64 bzip2-libs-1.0.6-26.el8.x86_64 capstone-4.0.2-5.el8.x86_64 cyrus-sasl-lib-2.1.27-6.el8_5.x86_64 elfutil
s-debuginfod-client-0.190-2.el8.x86_64 elfutils-libelf-0.190-2.el8.x86_64 elfutils-libs-0.190-2.el8.x86_64 glibc-2.28-251.0.2.el8_10.4.x86_64 krb5-libs-1.18.2-29.0.1.el8_10.x86_64 libco
m_err-1.46.2-2.el8.x86_64 libcurl-7.61.1-34.el8_10.2.x86_64 libgcc-8.5.0-22.0.1.el8_10.x86_64 libidn2-2.2.0-1.el8.x86_64 libnghttp2-1.33.0-6.el8_10.1.x86_64 libselinux-2.9-8.el8.x86_64
libssh-0.9.6-14.el8.x86_64 libstdc++-8.5.0-22.0.1.el8_10.x86_64 libunistring-0.9.9-3.el8.x86_64 libxcrypt-4.1.1-6.el8.x86_64 libzstd-1.4.4-1.0.1.el8.x86_64 ncurses-libs-6.1-10.20180224.
el8.x86_64 openldap-2.4.46-19.el8_10.x86_64 openssl-libs-1.1.1k-12.el8_9.x86_64 pcre2-10.32-3.el8_6.x86_64 xz-libs-5.2.4-4.el8_6.x86_64 zlib-1.2.11-25.el8.x86_64

(gdb) bt
#0  add_field (output_fields=0x668800 <output_fields>, field=0x0) at /home/opc/uftrace/utils/field.c:80
#1  0x0000000000444606 in setup_field (output_fields=0x668800 <output_fields>, opts=0x7fff7c6f0f00, setup_default_field=0x423c50 <setup_avg_total_field>,
    field_table=0x669460 <field_diff_table>, field_table_size=<optimized out>) at /home/opc/uftrace/utils/field.c:125
#2  0x000000000040a5c8 in report_diff (opts=0x7fff7c6f0f00, handle=0x7fff7c6f0ab0) at /home/opc/uftrace/cmds/report.c:471
#3  command_report (argc=<optimized out>, argv=<optimized out>, opts=opts@entry=0x7fff7c6f0f00) at /home/opc/uftrace/cmds/report.c:546
#4  0x0000000000405912 in main (argc=<optimized out>, argv=<optimized out>) at /home/opc/uftrace/uftrace.c:1558
(gdb) q

$ uftrace report --avg-total --diff=uftrace.data.old
Segmentation fault (core dumped)

**Comment by namhyung** [comment]
Hello, thanks for the report and sorry for the late reply.  I can reproduce the bug and will take a look.

**Comment by namhyung** [comment]
I found it missed {total,self}-stdv fields and caused the trouble.  Will fix it soon.
