### ISSUE TITLE
Segmentation Fault when using pthread_exit()

### ISSUE THREAD

**Issue by minchae** [namhyung/uftrace#242]
i found a segfault error when using pthread_exit()

*  target source

```c++
#include <stdio.h>
#include <pthread.h>
#include <stdlib.h>
#include <unistd.h>

#define NUM_THREAD 4

pthread_t threads[10];
void *thread_main(void *);

int main(void)
{
	int i,rc,status,x[NUM_THREAD]={0,};

	printf("pid=%d\n", (int)getpid());

	for (int i = 0; i < NUM_THREAD; i++){
		x[i] = i;
		pthread_create(&threads[i], NULL, &thread_main, (void *)x[i]);
	}

	for (int i = 0; i < NUM_THREAD; i++){
		rc = pthread_join(threads[i], (void **)&status);
	}
	return 0;
}

inline void *thread_main(void *arg)
{
	float result = 0;
	for (int i = 0; i < 2; i++)
	{
		result = result + (double)random();
	}
	printf("thread: %d, result = %f\n", arg, result);
	pthread_exit((void *)0);
}
```
* result
```
```

* result by uftrace
```
$ uftrace ./target
=================================================
pid=8531
thread: 2, result = 2651220224.000000
process crashed by signal 11: Segmentation fault (si_code: 128)
child terminated by signal: 11: Segmentation fault
# DURATION    TID     FUNCTION
   0.459 us [ 8531] | __monstartup();
   0.387 us [ 8531] | __cxa_atexit();
            [ 8531] | main() {
   0.301 us [ 8531] |   getpid();
   2.710 us [ 8531] |   printf();
  16.553 us [ 8531] |   pthread_create();
   8.896 us [ 8531] |   pthread_create();
  11.488 us [ 8531] |   pthread_create();
   9.841 us [ 8531] |   pthread_create();
            [ 8535] | thread_main() {
   1.270 us [ 8535] |   random();
   0.082 us [ 8535] |   random();
   4.288 us [ 8535] |   printf();
            [ 8535] |   pthread_exit() {
            [ 8536] | thread_main() {
   0.233 us [ 8536] |   random();
   0.061 us [ 8536] |   random();

uftrace stopped tracing with remaining functions
================================================
task: 8531
[0] main

task: 8535
[1] pthread_exit
[0] thread_main

task: 8536
[0] thread_main
```

this is an unusual case when using double and float type and print it.

I think this problem caused by pthread_exit (), which refers to where thread memory is invalied.

but, segfault does not appear when using int type without  double type

is this a problem that i think is right? or is it a different error?

**Comment by namhyung** [comment]
Thanks for the report.  I was able to reproduce and it seems there's problem during stack unwind by `pthread_exit()`.  I think we need to restore the original return addresses when calling pthread_exit().

```
(gdb) bt
#0  x86_64_fallback_frame_state (context=0x7f9aa3150cc0, context=0x7f9aa3150cc0, fs=0x7f9aa3150a10) at ./md-unwind-support.h:58
#1  uw_frame_state_for (context=context@entry=0x7f9aa3150cc0, fs=fs@entry=0x7f9aa3150a10) at /build/gcc/src/gcc/libgcc/unwind-dw2.c:1257
#2  0x00007f9aa3963d97 in _Unwind_ForcedUnwind_Phase2 (exc=exc@entry=0x7f9aa3152d70, context=context@entry=0x7f9aa3150cc0)
    at /build/gcc/src/gcc/libgcc/unwind.inc:155
#3  0x00007f9aa3964335 in _Unwind_ForcedUnwind (exc=0x7f9aa3152d70, stop=0x7f9aa4e41370 <unwind_stop>, stop_argument=<optimized out>)
    at /build/gcc/src/gcc/libgcc/unwind.inc:207
#4  0x00007f9aa4e41511 in __pthread_unwind () from /usr/lib/libpthread.so.0
#5  0x00007f9aa4e392f5 in pthread_exit () from /usr/lib/libpthread.so.0
#6  0x0000561e61aefa1e in thread_main (arg=0x1) at th5.c:25
#7  0x00007f9aa4e3808a in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007f9aa4b6f47f in clone () from /usr/lib/libc.so.6
```

**Comment by namhyung** [comment]
The fix was pushed to [check/pthread-fix](https://github.com/namhyung/uftrace/compare/check/pthread-fix).
