### ISSUE TITLE
reading symbols will be fail if target has no section header.

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#412]
while reading symbols from each modules, iterating section header to find its string tab. when this time, if target module has no section header or string table, like 'ld.so.cache'. it will be crashed. 
```
 55 void elf_get_strtab(struct uftrace_elf_data *elf,
 56                     struct uftrace_elf_iter *iter,
 57                     int shidx)
 58 {
 59         Elf_Shdr *shdr = elf->file_map + elf->ehdr.e_shoff;
 60
 61         iter->strtab = elf->file_map + shdr[shidx].sh_offset;
 62 }
```

```
 91 #define elf_for_each_shdr(elf, iter)                                    \
 92         for (elf_get_strtab((elf), (iter), (elf)->ehdr.e_shstrndx),     \
 93                      (iter)->i = 0, (iter)->nr = (elf)->ehdr.e_shnum;   \
 94              (iter)->i < (iter)->nr &&                                  \
 95                      memcpy(&(iter)->shdr,                              \
 96                             (elf)->file_map + (elf)->ehdr.e_shoff +     \
 97                             (iter)->i * (elf)->ehdr.e_shentsize,        \
 98                             (elf)->ehdr.e_shentsize);                   \
 99              (iter)->i++)
```

it can be fixed simply by add simple validation logic.
how do you think?

**Comment by namhyung** [comment]
Sure, please send a PR.  Does this problem exist only in the raw ELF code?

**Comment by ParkHanbum** [comment]
@namhyung I think it is occured in raw-elf only, because when I test it in another system that has installed libelf did not crashed. but I'll review it again, and notice to you.

**Comment by namhyung** [comment]
OK, fot testing you can run `configure --without-libelf` to disable it.

**Comment by ParkHanbum** [comment]
```
Core was generated by `./uftrace dynamic -L/home/m/git/attach -d /home/m/git/attach/test --pid=2511'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000417da2 in elf_get_strtab (elf=elf@entry=0x7ffd995eeb10,
    iter=iter@entry=0x7ffd995eeb70, shidx=0)
    at /home/m/git/attach/utils/symbol-rawelf.c:61
61              iter->strtab = elf->file_map + shdr[shidx].sh_offset;
warning: File "/home/m/git/attach/uftrace-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /home/m/git/attach/uftrace-gdb.py
line to your configuration file "/home/m/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/m/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
(gdb) bt
#0  0x0000000000417da2 in elf_get_strtab (elf=elf@entry=0x7ffd995eeb10,
    iter=iter@entry=0x7ffd995eeb70, shidx=0)
    at /home/m/git/attach/utils/symbol-rawelf.c:61
    at /home/m/git/attach/utils/symbol.c:302
#2  0x000000000043038d in load_module_symtabs (
    symtabs=symtabs@entry=0x7ffd995eed60)
    at /home/m/git/attach/utils/symbol.c:930
#3  0x0000000000416b42 in save_session_symbols (opts=0x7ffd995ef150)
    at /home/m/git/attach/cmds/record.c:1374
#4  write_symbol_files (wd=0x7ffd995eee30, opts=0x7ffd995ef150)
    at /home/m/git/attach/cmds/record.c:1812
#5  do_main_loop (pfd=pfd@entry=0x7ffd995eeff8, ready=ready@entry=5,
    opts=opts@entry=0x7ffd995ef150, pid=<optimized out>)
    at /home/m/git/attach/cmds/record.c:1886
#6  0x0000000000408534 in command_dynamic (argc=<optimized out>,
    argv=argv@entry=0x7ffd995ef3c8, opts=opts@entry=0x7ffd995ef150)
    at /home/m/git/attach/cmds/dynamic.c:448
#7  0x00000000004045b2 in main (argc=0, argv=0x7ffd995ef3c8)
    at /home/m/git/attach/uftrace.c:1080
(gdb) p elf
$1 = (struct uftrace_elf_data *) 0x7ffd995eeb10
(gdb) p elf->file_map
$2 = (void *) 0x7f2511452000
(gdb) p elf->ehdr.e_shoff
$3 = 44006234915587
(gdb) p shdr
$4 = (Elf_Shdr *) 0xa72b11452303
(gdb) list
56                          struct uftrace_elf_iter *iter,
57                          int shidx)
58      {
59              Elf_Shdr *shdr = elf->file_map + elf->ehdr.e_shoff;
60
61              iter->strtab = elf->file_map + shdr[shidx].sh_offset;
62      }
63
64      void elf_get_secdata(struct uftrace_elf_data *elf,
65                           struct uftrace_elf_iter *iter)
(gdb) x/i $rip
=> 0x417da2 <elf_get_strtab+18>:        add    0x18(%rax),%rcx
(gdb) info reg $rax
rax            0xa72b11452303   183803415175939
(gdb)
```

that results not different what expected.
this issue only occurred with rawelf.

The above test results were generated by the attach feature. because ld.so.cache injected after uftrace stuff done. so, this issue effect only in specially situlation.

but still this issue meaningful because the module that has abnormal elfheader to provide specific usability can be exist.

do you still agree with the needs to fix this issue?

**Comment by namhyung** [comment]
Yes I think this is still needed as section headers are optional and we need to protect it from accessing out of range of the file.

**Comment by ParkHanbum** [comment]
```
+  55 static int validate_ehdr(struct uftrace_elf_data *elf)
+  56 {
+  57         uint64_t mapped_addr = (uint64_t)elf->file_map;
+  58         uint64_t mapped_size = elf->file_size;
+  59         uint64_t mapped_end = mapped_addr + mapped_size;
+  60         Elf_Ehdr ehdr = elf->ehdr;
+  61
+  62
+  63         if (ehdr.e_phnum == 0 || ehdr.e_phentsize == 0)
+  64                 return -1;
+  65         if (ehdr.e_shnum == 0 || ehdr.e_shentsize == 0)
+  66                 return -1;
+  67
+  68         if (mapped_addr + ehdr.e_shoff + ehdr.e_shnum * ehdr.e_shentsize
+  69                         > mapped_end)
+  70                 return -1;
+  71
+  72         if (mapped_addr + ehdr.e_phoff + ehdr.e_phnum * ehdr.e_phentsize
+  73                         > mapped_end)
+  74                 return -1;
+  75
+  76         return 0;
+  77 }
```
I wrote an elf header verification code. What do you think?
need to validate its header before build elf module list.

**Comment by namhyung** [comment]
It's legitimate for an ELF file not having section headers so you should not fail such cases.  But we need a way to disable iterating section headers somehow.

**Comment by ParkHanbum** [comment]
```
  int elf_init(const char *filename, struct uftrace_elf_data *elf)
  {
          struct stat stbuf;

          elf->fd = open(filename, O_RDONLY);
          if (elf->fd < 0)
                  return -1;

          if (fstat(elf->fd, &stbuf) < 0)
                  goto err;

          elf->file_size = stbuf.st_size;

          elf->file_map = mmap(NULL, elf->file_size, PROT_READ, MAP_PRIVATE,
                               elf->fd, 0);
          if (elf->file_map == MAP_FAILED)
                  goto err;

          memcpy(&elf->ehdr, elf->file_map, sizeof(elf->ehdr));

+         if (elf_validation(elf) < 0) {
+                 goto err;
+         }
```

```
+ /*
+  *  ELF File Header validation logic.
+  */
+ int elf_validation(struct uftrace_elf_data *elf)
+ {
+         Elf_Ehdr *ehdr;
+         int eclass, data, version;
+         int res = 0;
+         unsigned long mapped_saddr, mapped_eaddr, mapped_size;
+
+         ehdr = &elf->ehdr;
+         // validate ELF Magic.
+         if (memcmp(ehdr, ELFMAG, SELFMAG)) {
+                 pr_dbg("ELF Signature not matched\n");
+                 res = -1;
+         }
+
+         // validate some field of elf header.
+         eclass = (int) ((unsigned char *) ehdr)[EI_CLASS];
+         data = (int) ((unsigned char *) ehdr)[EI_DATA];
+         version = (int) ((unsigned char *) ehdr)[EI_VERSION];
+
+         if (!(eclass > ELFCLASSNONE && eclass < ELFCLASSNUM)) {
+                 pr_dbg("eclass out of range %d | Your:[%d] | %d\n",
+                                 ELFCLASSNONE, eclass, ELFCLASSNUM);
+                 res = -1;
+         }
+
+         if (!(data > ELFDATANONE && data < ELFDATANUM)) {
+                 pr_dbg("data out of range %d | Your:[%d] | %d\n",
+                                 ELFDATANONE, data, ELFDATANUM);
+                 res = -1;
+         }
+
+         if (!(version > EV_NONE && version < EV_NUM)) {
+                 pr_dbg("version out of range %d | Your:[%d] | %d\n",
+                                 EV_NONE, version, EV_NUM);
+                 res = -1;
+         }
+
+         // validate ELF file size.
+         mapped_saddr = (long)elf->file_map;
+         mapped_size = elf->file_size;
+         mapped_eaddr = mapped_saddr + mapped_size;
+
+         if (ehdr->e_phnum == 0 || ehdr->e_phentsize == 0) {
+                 pr_dbg("Program section must exist in ELF.\n");
+                 res = -1;
+         }
+
+         if (ehdr->e_shnum > 0 && ehdr->e_shentsize == 0) {
+                 pr_dbg("Section header size cannot be 0.\n");
+                 res = -1;
+         }
+
+         if (mapped_saddr + ehdr->e_shoff +
+                         ehdr->e_shnum * ehdr->e_shentsize
+                         > mapped_eaddr) {
+                 pr_dbg("Section header address over the file size\n");
+                 res = -1;
+         }
+
+         if (mapped_saddr + ehdr->e_phoff +
+                         ehdr->e_phnum * ehdr->e_phentsize
+                         > mapped_eaddr) {
+                 pr_dbg("Program header address over the file size\n");
+                 res = -1;
+         }
+
+         return res;
+ }
```
I was add more logic that Excerpt from libelf to validate ELF. 
maybe this enough to validate malformed elf file. 
do you have feedback?
