### ISSUE TITLE
Null Pointer Dereference in read_taskinfo()

### ISSUE THREAD

**Issue by gy741** [namhyung/uftrace#574]
Hello,

If the ```taskinfo:tids``` are corrupted in ```info``` file, a memory error occurs.

I think, Exception handling seems necessary in read_taskinfo()

Thanks.

In my opinion, Fix code:
```diff
diff --git a/cmds/info.c b/cmds/info.c
index 61f68a7..38c0817 100644
--- a/cmds/info.c
+++ b/cmds/info.c
@@ -553,6 +553,8 @@ static int read_taskinfo(void *arg)
                        assert(nr_tid == info->nr_tid);
                }
        }
+       if (info->tids == NULL)
+               goto out;
        ret = 0;
 out:
        free(buf);
```

testcase(info file):
```
taskinfo:?ids=8429
```

gdb log:
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555557209c in process_uftrace_info (handle=0x7fffffffdd50, 
    opts=0x7fffffffdf90, process=0x555555571a4d <print_info>, data=0x0)
    at /home/karas/uftrace/cmds/info.c:1031
1031				int tid = info->tids[i];
(gdb) bt
#0  0x000055555557209c in process_uftrace_info (handle=0x7fffffffdd50, 
    opts=0x7fffffffdf90, process=0x555555571a4d <print_info>, data=0x0)
    at /home/karas/uftrace/cmds/info.c:1031
#1  0x0000555555572817 in command_info (argc=0, argv=0x7fffffffe1e8, 
    opts=0x7fffffffdf90) at /home/karas/uftrace/cmds/info.c:1135
#2  0x000055555555d555 in main (argc=0, argv=0x7fffffffe1e8)
    at /home/karas/uftrace/uftrace.c:1072
```

**Comment by namhyung** [comment]
I think the following is better:

```diff
diff --git a/cmds/info.c b/cmds/info.c
index 90c75e84..dd930209 100644
--- a/cmds/info.c
+++ b/cmds/info.c
@@ -552,6 +553,8 @@ static int read_taskinfo(void *arg)

                        assert(nr_tid == info->nr_tid);
                }
+               else
+                       goto out;
        }
        ret = 0;
 out:
```
