### ISSUE TITLE
The mcount initialization consumes too much time.

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#584]
I'm trying to inject the shared object to running process. I think i have success to this, but initialization of libmcount need too much time to keep process alive. so, when trying to inject libmcount shared object then receive the SIGPROF. 

this is log about this issue.

```
$ ./injector libmcount-dynamic.so 59797 59798 0x601074 1
I just got loaded
injector: size of code chunk : 88
injector: Address to inject : 400fa8
injector: Address = 601074
injector: data = 35b292c34c023528
injector: instead of expected SIGTRAP, target stopped with signal 27: Profiling timer expired
injector: sending process 59797 a SIGSTOP signal for debugging purposes
injector: ptrace.c:113:check_target_sig
```

```
(gdb) bt
#0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:249
#1  0x00007fac6b3c09f7 in sort_symtab (symtab=0x1ad6950)
    at /home/m/git/myuftrace/utils/symbol.c:262
#2  load_symtab (symtab=symtab@entry=0x1ad6950,
    filename=filename@entry=0x1ad69c0 "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25", offset=<optimized out>, flags=flags@entry=5)
    at /home/m/git/myuftrace/utils/symbol.c:353
#3  0x00007fac6b3c1f4a in load_module_symtabs (
    symtabs=symtabs@entry=0x7fac6b5d35a0 <symtabs>)
    at /home/m/git/myuftrace/utils/symbol.c:950
#4  0x00007fac6b3a8583 in mcount_filter_init (force=false,
    dirname=0x1ac0bdc "/home/m/git/attach/xxx", ptype=PATT_REGEX)
    at /home/m/git/myuftrace/libmcount/mcount.c:136
#5  mcount_startup () at /home/m/git/myuftrace/libmcount/mcount.c:1362
#6  mcount_init () at /home/m/git/myuftrace/libmcount/mcount.c:1485
#7  0x00007fac6c5fb733 in call_init (env=0x7ffcc30749e8, argv=0x7ffcc30749d8, argc=1,
    l=<optimized out>) at dl-init.c:72
#8  _dl_init (main_map=main_map@entry=0x1abc020, argc=1, argv=0x7ffcc30749d8,
    env=0x7ffcc30749e8) at dl-init.c:119
#9  0x00007fac6c6001ff in dl_open_worker (a=a@entry=0x7ffcc3074650) at dl-open.c:522
#10 0x00007fac6bf3e2df in __GI__dl_catch_exception (
    exception=exception@entry=0x7ffcc3074630,
    operate=operate@entry=0x7fac6c5ffdc0 <dl_open_worker>,
    args=args@entry=0x7ffcc3074650) at dl-error-skeleton.c:196
#11 0x00007fac6c5ff7ca in _dl_open (
    file=0x1abbf70 "/home/m/git/linux_so_injector/libmcount-dynamic.so",
    mode=-2147483647, caller_dlopen=0x400fd5, nsid=<optimized out>, argc=1,
    argv=<optimized out>, env=0x7ffcc30749e8) at dl-open.c:605
#12 0x00007fac6c3e7f96 in dlopen_doit (a=a@entry=0x7ffcc3074880) at dlopen.c:66
```

as you can see, it has been stopped while initialization because it have received SIGPROF. if there is no way to ignore SIGPROF, this work must doing after initialized. how do you think?

**Comment by namhyung** [comment]
I have no idea why it gets SIGPROF.  Is it the kernel or your program send the signal?

**Comment by ParkHanbum** [comment]
I think it comes from the kernel. Previously successful injecting libmcount consumed 2 seconds to initialize. if I make this time more long, by using verbose option like -vvv, then it has been failed. so, I think if initialization takes time too long then it will receive the sigprof.

**Comment by namhyung** [comment]
It may be sent from glibc (gprof) to sample PC for profiling.

**Comment by ParkHanbum** [comment]
@namhyung OK, Now I see. we cannot ignore this still. right?

**Comment by ParkHanbum** [comment]
this issue closed by updated commits
