### ISSUE TITLE
tui: hidden Time(Duration) with '-f none' occurs seg fault.

### ISSUE THREAD

**Issue by DanielTimLee** [namhyung/uftrace#628]
As issue title presents, using `-f none` causes a segfault.

```bash
$ uftrace tui -f none
Segmentation fault (core dumped)
```

**Comment by honggyukim** [comment]
It's caused due to null pointer dereference.
```
1047│ static void print_graph_indent(struct tui_graph *graph,
1048│                                struct tui_graph_node *node,
1049│                                int depth, bool single_child)
1050│ {
1051│         int i;
1052├───────> struct tui_graph_node *parent = (void *)node->n.parent;
1053│
1054│         for (i = 0; i < depth; i++) {
1055│                 if (!graph->disp_mask[i]) {
1056│                         printw("   ");
1057│                         continue;
1058│                 }
1059│
1060│                 if (i < depth - 1 || single_child)
1061│                         printw("  │");
1062│                 else if (is_last_child(parent, node))
1063│                         printw("  └");
1064│                 else
1065│                         printw("  ├");
1066│         }
1067│ }

(gdb) p node
$1 = (struct tui_graph_node *) 0x0
```
Here is the backtrace info.
```
(gdb) bt
#0  0x0000000000411dfc in print_graph_indent (graph=0x79fed0, node=0x0, depth=0, single_child=true) at /home/honggyu/work/uftrace/git/uftrace/cmds/tui.c:1052
#1  0x0000000000411f22 in win_display_graph (win=0x79fed0, node=0x0) at /home/honggyu/work/uftrace/git/uftrace/cmds/tui.c:1082
#2  0x0000000000413e1c in tui_window_display (win=0x79fed0, full_redraw=true, handle=0x7fffffffdef0) at /home/honggyu/work/uftrace/git/uftrace/cmds/tui.c:1887
#3  0x0000000000415499 in tui_main_loop (opts=0x7fffffffe130, handle=0x7fffffffdef0) at /home/honggyu/work/uftrace/git/uftrace/cmds/tui.c:2477
#4  0x00000000004156e2 in command_tui (argc=0, argv=0x7fffffffe388, opts=0x7fffffffe130) at /home/honggyu/work/uftrace/git/uftrace/cmds/tui.c:2535
#5  0x000000000040763c in main (argc=0, argv=0x7fffffffe388) at /home/honggyu/work/uftrace/git/uftrace/uftrace.c:1085
```
