### ISSUE TITLE
case about using jump to move to the function

### ISSUE THREAD

**Issue by ParkHanbum** [namhyung/uftrace#812]
I was trace the v8 javascript engine. while interpreting javascript, there is weird problem. I was debug this problem to find what is the making problem. the cause of problem is that v8 interpreter use jump-op instead call-op to move to another function. this is break the rule about calling-conversion. uftrace will not operate normally due to a jump call that does not follow the calling convention.

see belows:
```
Thread 2.1 "d8" received signal SIGSEGV, Segmentation fault.
0x000055555601524a in Builtins_CallFunction_ReceiverIsAny ()
(gdb) bt
#0  0x000055555601524a in Builtins_CallFunction_ReceiverIsAny ()
#1  0x00007ffff7bbcd0d in __dentry__ () at /home/m/git/uftrace/arch/x86_64/dynamic.S:110
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

```
# from uftrace
(gdb) x/10gx $rsp
0x7fffffffd468: 0x00007ffff7bbcd0d      0x0000000100000000
0x7fffffffd478: 0x000055555601bd37      0x0000000100000000
0x7fffffffd488: 0x000003832cd804d1      0x000018e2fb59e9e1
0x7fffffffd498: 0x000003832cd804d1      0x0000005500000000
0x7fffffffd4a8: 0x000018e2fb59e8b1      0x000018e2fb59e941
```

```
# from d8
(gdb) x/10gx $rsp
0x7fffffffd658: 0x000055555601bd37      0x0000000100000000
0x7fffffffd668: 0x0000320d30a004d1      0x0000000100000000
0x7fffffffd678: 0x0000320d30a004d1      0x00000eea7019e9e1
0x7fffffffd688: 0x0000320d30a004d1      0x0000005500000000
0x7fffffffd698: 0x00000eea7019e8b1      0x00000eea7019e941
```

d8 must refer the address which located 3rd of stack.
in uftrace case, that is 0x7fffffffd478. and in d8 case, that is 0x7fffffffd668.

in d8 case, that address point the somewhere of the heap.
but uftrace case, that address point middle of the function.

```
(gdb) x/i 0x000055555601bd37
   0x55555601bd37 <Builtins_InterpreterEntryTrampoline+695>:    mov    r14,QWORD PTR [rbp-0x18]
```

this address come from the last of the call.
```
   0x000055555601bd35 <+693>:   call   rcx
   0x000055555601bd37 <+695>:   mov    r14,QWORD PTR [rbp-0x18]
```

uftrace replace that address from here :
```
// libmcount/misc.c:212
*prev_rstack->parent_loc = parent_ip;
```

**Comment by ParkHanbum** [comment]
this is not a bug report, uftrace worked fine. 
I wonder that uftrace want to support these cases.

**Comment by namhyung** [comment]
I think the tail-call optimization converts a call to a jump.  And uftrace is fine with it.

**Comment by ParkHanbum** [comment]
@namhyung what 

> 
> 
> I think the tail-call optimization converts a call to a jump. And uftrace is fine with it.

what does 'fine' mean?

**Comment by ParkHanbum** [comment]
anyway, it works after turn-off AUTO_RECOVER

```
$ git diff
diff --git a/arch/x86_64/mcount-arch.h b/arch/x86_64/mcount-arch.h
index a0bafff9..5651673e 100644
--- a/arch/x86_64/mcount-arch.h
+++ b/arch/x86_64/mcount-arch.h
@@ -32,7 +32,7 @@ struct mcount_arch_context {
 #define ARCH_PLT0_SIZE  16
 #define ARCH_PLTHOOK_ADDR_OFFSET  6

-#define ARCH_SUPPORT_AUTO_RECOVER  1
+#define ARCH_SUPPORT_AUTO_RECOVER  0
 #define ARCH_CAN_RESTORE_PLTHOOK   1

 struct plthook_arch_context {
```

results:
```
   0.256 us [ 93586] | v8::internal::EmbeddedData::InstructionStartOfBuiltin();
            [ 93586] | Builtins_JSEntry() {
            [ 93586] |   Builtins_JSEntryTrampoline() {
            [ 93586] |     Builtins_CallFunction_ReceiverIsAny() {
            [ 93586] |       Builtins_InterpreterEntryTrampoline() {
            [ 93586] |         Builtins_LdaConstantHandler() {
            [ 93586] |           Builtins_LdaZeroHandler() {
            [ 93586] |             Builtins_MovHandler() {
            [ 93586] |               Builtins_CallRuntimeHandler() {
            [ 93586] |                 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvInRegister_NoBuiltinExit() {
   0.181 us [ 93586] |                   v8::internal::Builtins::builtin();
   6.847 us [ 93586] |                 } /* Builtins_CEntry_Return1_DontSaveFPRegs_ArgvInRegister_NoBuiltinExit */
            [ 93586] |                 Builtins_StackCheckHandler() {
            [ 93586] |                   Builtins_LdaUndefinedHandler() {
            [ 93586] |                     Builtins_LdaGlobalHandler() {
            [ 93586] |                       Builtins_LdaSmiHandler() {
            [ 93586] |                         Builtins_CallNoFeedbackHandler() {
            [ 93586] |                           Builtins_InterpreterPushArgsThenCall() {
            [ 93586] |                             Builtins_CallFunction_ReceiverIsAny() {
            [ 93586] |                               Builtins_CompileLazy() {
            [ 93586] |                                 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit() {
   0.302 us [ 93586] |                                   v8::internal::Builtins::builtin();
  23.898 us [ 93586] |                                 } /* Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit */
            [ 93586] |                                 Builtins_InterpreterEntryTrampoline() {
```

**Comment by ParkHanbum** [comment]
@namhyung I wonder why AUTO_RECOVER is needed.

**Comment by honggyukim** [comment]
@ParkHanbum Please read #418. The problem was found when tracing node.js engine.

**Comment by honggyukim** [comment]
If you disable auto-recover, then node will get crashed when it tries to perform garbage collection.

**Comment by ParkHanbum** [comment]
@honggyukim I see, I'll find the way.

**Comment by namhyung** [comment]
AFAIK uftrace can handle tail-calls without problem.  But it's strange that it's used for other cases..
